name: Check broken URLs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 1 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@ab177d40ee5483edb974554986f56b33477e21d0 # https://github.com/ruby/setup-ruby/releases/tag/v1.265.0
        with:
          bundler-cache: true
          cache-version: 0

      - name: Build with Jekyll
        run: bundle exec jekyll build

      - name: Check URLs
        shell: bash
        run: docker run --rm -u $(id -u):$(id -g) -v "$PWD":/mnt ghcr.io/linkchecker/linkchecker:10.6.0 /mnt/_site/ \
          --file-output=failures/utf-8//mnt/failures.log \
          --timeout=5 \
          --ignore-url='^mailto:' \
          --recursion-level=5
