on:
  schedule:
    - cron: '0 8 1 * *'
  pull_request:
    types: [ labeled ]

permissions:
  contents: read
  pull-requests: read

name: Check URLs
jobs:
  my-broken-link-checker:
    if: |
      github.event_name != 'pull_request' ||
      github.event.label.name == 'link check'
    name: Run broken link checker
    runs-on: ubuntu-latest

    steps:
      - name: Run mybrokenlinkchecker (filter out internal errors)
        shell: bash
        continue-on-error: true
        run: |
          docker run --rm \
            raviqqe/muffet:latest \
            https://www.expressjs.com \
            --buffer-size=65536 \
            --max-connections-per-host=1 \
            --timeout=10 \
            --color=always \
            --ignore-fragments \
            --accepted-status-codes='200..300,403,429' \
            2>&1 \ 
            | grep -vE 'https?://([a-z0-9-]+\.)?expressjs\.com(/|$)' \
            | sort -u || true
